version: '3'
services:
    nginx:
        image: nginx:1.15
        ports:
            - 80:80
        volumes:
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build: ./php-fpm
        volumes:
            - ./source:/var/www/html
            - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: password
            TZ: Asia/Tokyo
        ports:
            - 3306:3306
    redis:
        image: redis
        ports:
            - 6379:6379
