version: '3'
services:
    nginx:
        image: nginx:1.15
        ports:
            - 80:80
        volumes:
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build: ./php-fpm
        volumes:
            - ./source:/var/www/html
            - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: password
            TZ: Asia/Tokyo
        ports:
            - 3306:3306
    redis:
        image: redis
        ports:
            - 6379:6379
    minio:
        image: minio/minio
        ports:
            - 9000:9000
        environment:
            MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
            MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
        command: server /export
    createbuckets: # デフォルトバケット作成用のコンテナ
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add minio ${AWS_URL} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
            /usr/bin/mc rm -r --force minio/${AWS_BUCKET};
            /usr/bin/mc mb minio/${AWS_BUCKET};
            /usr/bin/mc policy download minio/${AWS_BUCKET};
            exit 0;
            "
